### ISSUE TITLE
Build Error on Windows 11

### ISSUE THREAD

**Issue by Suleman-Elahi** [newlooper/VirtualSpace#1]
![image](https://user-images.githubusercontent.com/24384996/159473968-7cc14bd9-cb17-45b4-836f-91b27cae1d2a.png)

**Comment by newlooper** [comment]
three way to fix this:
- pwsh.exe is powershell 7.x, just install it.
- if you have powershell 5.x or 6.x in your system, edit the WPF\ControlPanel\ControlPanel.csproj, change pwsh.exe to powershell.exe
- WPF\ControlPanel is currently  not used by VirtualSpace, unload it in your IDE
