### ISSUE TITLE
mainview failes to be fullscreen if connecting to a larger screen

### ISSUE THREAD

**Issue by Zplusless** [newlooper/VirtualSpace#10]
Start virtualspace on a 15.6 inch laptop. Then connect the laptop to a 27 inch screen. The mainview looks like bellow instead of fullscreen

![image](https://user-images.githubusercontent.com/10062702/199685990-8f163aab-3424-4166-bd3d-7828cc128532.png)

restart virtualspace can fix it.

**Comment by newlooper** [comment]
download the lastest version and try rise MainView after connect another screen.

**Comment by Zplusless** [comment]
problem solved! Appreciate your quick reply!
兄弟牛逼
