### ISSUE TITLE
File Access Error when trying to open the application...

### ISSUE THREAD

**Issue by direrFlood** [newlooper/VirtualSpace#11]
![Clip_20221106_120306](https://user-images.githubusercontent.com/110556802/200164748-9e6d3128-d796-42b6-a3f7-083253d0c39f.png)

**Comment by newlooper** [comment]
hmmm~

lack of information, but i suggest you could put VirtualSpace dir in another folder whos path not include 'OneDrive - Technion' and try again.

eg. your desktop.

**Comment by direrFlood** [comment]
use folder name is the problem. Maybe you should check about white spaces in the program...
