### ISSUE TITLE
Does the window support Chinese？

### ISSUE THREAD

**Issue by xiao-peng-yu** [newlooper/VirtualSpace#113]
The current readme+windows are all in English and are not friendly to Chinese users. Can they be supported in the future.

**Comment by newlooper** [comment]
是多语言的，中文演示在B站
https://www.bilibili.com/video/BV1yP4y197tP

**Comment by xiao-peng-yu** [comment]
> 是多语言的，中文演示在B站 https://www.bilibili.com/video/BV1yP4y197tP

I have watched the video - but I am not sure how to use it.

Can the function window support Chinese？

![image](https://github.com/newlooper/VirtualSpace/assets/68453850/c7dca57b-ed50-4eb9-80bc-a32ff6554d60)

![image](https://github.com/newlooper/VirtualSpace/assets/68453850/38d44923-782b-49da-9160-bbe15008081f)

**Comment by newlooper** [comment]
没显示全，最大化一下，在左下角有个齿轮⚙️

**Comment by xiao-peng-yu** [comment]
> 没显示全，最大化一下，在左下角有个齿轮⚙️

Found it, there is a problem with the default download interface display.
Thank you very much for the author's response

![image](https://github.com/newlooper/VirtualSpace/assets/68453850/cbde76b8-d508-4694-a219-9794f77ba721)

After setting the theme, there are no issues with the interface display anymore
![image](https://github.com/newlooper/VirtualSpace/assets/68453850/9e584167-2208-4285-b3f3-7b4a22191eee)

**Comment by xiao-peng-yu** [comment]
I hope readme can provide more detailed explanations. By the way, it supports Chinese language
