### ISSUE TITLE
Still not working on Windows 11 22H2

### ISSUE THREAD

**Issue by kranix0** [newlooper/VirtualSpace#115]
I spoke too soon on #111 – VirtualSpace still doesn't work. I tried running a freshly downloaded copy of the latest version. It executed and successfully created its files, but then it exited.

There is nothing helpful in the logs. Is there a way to force it into taking more detailed logs?

Edition	Windows 11 Pro
Version	22H2
Installed on	‎Tue ‎14/‎02/‎2023
OS build	22621.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by newlooper** [comment]
- update windows to 23H2 (OS 22631.xxxx)
OR
- find a old version of VirtualSpace which support 22H2

**Comment by kranix0** [comment]
Thank you for pointing that out! Windows Update still gives regular updates, so I assumed that all was well and I didn't notice that the base OS was still stuck on 2022. I'll work out how to force the 23H2 update.
