### ISSUE TITLE
After the enterprise wechat is added to the rule, open the context menu with the right mouse button, and the menu will keep blinking

### ISSUE THREAD

**Issue by wozaibeijizhuxueya** [newlooper/VirtualSpace#120]
![image](https://github.com/newlooper/VirtualSpace/assets/161796546/0320ad37-7a2f-4099-8b63-73b2d8e2676e)
I am a Chinese user. In the process of using enterprise wechat, I found that if I opened this software, when the cursor was in the input box of the enterprise, I could not open the context menu through the right mouse button, because the context menu would keep blinking. If the enterprise wechat app was removed from the rules of the virtual space app, the context menu bar could be displayed normally, which is a bug. This is the first time for me to submit a bug, because this virtual space software solved my big problem, I am very grateful to the developer of this software, I love this virtual space software.

**Comment by newlooper** [comment]
`mark`
will fix in next version.

`标记`
将在下一个版本修复。

**Comment by wozaibeijizhuxueya** [comment]
Thanks a lot！







---- Replied Message ----
| From | Dylan ***@***.***> |
| Date | 4/16/2024 15:30 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [newlooper/VirtualSpace] After the enterprise wechat is added to the rule, open the context menu with the right mouse button, and the menu will keep blinking (Issue #120) |

mark
will fix in next version.

标记
将在下一个版本修复。
