### ISSUE TITLE
Every time a message notifies you to refresh or refresh the browser page, an error pops up

### ISSUE THREAD

**Issue by wozaibeijizhuxueya** [newlooper/VirtualSpace#121]
![image](https://github.com/newlooper/VirtualSpace/assets/161796546/3cdddc39-12fd-4865-8510-f480bd1ab01b)

**Comment by newlooper** [comment]
规则的条件定义的太宽泛了，比如：只定义了程序名，而没有其他条件，就容易出现这类情况。

不过，鉴于浏览器程序的重要性和常用性，后续版本的 `VS` 会对主流浏览器(Chrome, Firefox...)做出特殊处理，以避免闹人的报警。

**Comment by wozaibeijizhuxueya** [comment]
What a quick response. Thumbs up for you




---- Replied Message ----
| From | Dylan ***@***.***> |
| Date | 4/16/2024 16:53 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [newlooper/VirtualSpace] Every time a message notifies you to refresh or refresh the browser page, an error pops up (Issue #121) |

规则的条件定义的太宽泛了，比如：只定义了程序名，而没有其他条件，就容易出现这类情况。

不过，鉴于浏览器程序的重要性和常用性，后续版本的 VS 会对主流浏览器(Chrome, Firefox...)做出特殊处理，以避免闹人的报警。
