### ISSUE TITLE
【功能建议】关于Win+Tab后虚拟桌面中窗口的排列

### ISSUE THREAD

**Issue by 0xf581d2** [newlooper/VirtualSpace#123]
在三个窗口时，窗口会如下排列：
| 1 | 2 | 3 |

如果是八个窗口的时候：
| 1 | 2 | 3 | 4 |
----间距----
| 5 | 6 | 7 | 8 |

这样做有时候会让窗口过于小，然后“心理”上的感觉点不到想要进入的窗口。

有没有可能使用一种“异形”的排列方式，比如：
&nbsp;&nbsp;| 1 |
| 2 | 3 |

这样就可以更有效地使用余下的空间了……

**Comment by mdear** [comment]
Translation:

When there are three windows, the windows will be arranged as follows:
| 1 | 2 | 3 |

If there are eight windows:
| 1 | 2 | 3 | 4 |
---- Spacing----
| 5 | 6 | 7 | 8 |

This sometimes makes the windows too small, and then the "psychological" feeling cannot click on the window you want to enter.

Is it possible to use a "special" arrangement, such as:
| 1 |
| 2 | 3 |

This way, the remaining space can be used more effectively...
