### ISSUE TITLE
在主视图内不显示虚拟桌面下方和右方的边框

### ISSUE THREAD

**Issue by 0xf581d2** [newlooper/VirtualSpace#124]
如图：
![屏幕截图 2024-05-28 154613](https://github.com/newlooper/VirtualSpace/assets/49151698/af9bcee1-9e6b-4e76-801c-984c859087a3)
![屏幕截图 2024-05-28 154715](https://github.com/newlooper/VirtualSpace/assets/49151698/3f80d365-971e-4293-9b24-91009e17f9a0)

系统版本：
![屏幕截图 2024-05-28 155025](https://github.com/newlooper/VirtualSpace/assets/49151698/9ed69e40-e2e5-4ef5-987a-9e44f393f3f2)

其他信息：
![屏幕截图 2024-05-28 155343](https://github.com/newlooper/VirtualSpace/assets/49151698/82117772-8c3c-4302-887e-ac211efc98cd)
![屏幕截图 2024-05-28 155355](https://github.com/newlooper/VirtualSpace/assets/49151698/0f04fcac-fdd4-42fd-9b6d-bf3830486e34)

**Comment by mdear** [comment]
Translation of title:

Hide the borders at the bottom and right of the virtual desktop in the main view #124
