### ISSUE TITLE
Windows 11 24H2 not supported.

### ISSUE THREAD

**Issue by rowanmoor** [newlooper/VirtualSpace#129]
Windows 11 24H2 is now rolling out.  My PC updated automatically last night.  VirtualSpace reports it as an unsupported Windows Version and does not start.
![image](https://github.com/user-attachments/assets/4fe8ef70-0297-49d8-8a9c-f52b861d0229)

**Comment by mdear** [comment]
Agreed.  I miss VirtualSpace, it really helped improve my productivity.

**Comment by Zplusless** [comment]
same issue.

**Comment by ultrakorne** [comment]
same here :(

**Comment by Slider-Override** [comment]
looks like the project is dead ?

**Comment by newlooper** [comment]
Finally, M$ push 24H2 to my PC.
A new version of VS is published.
