### ISSUE TITLE
开机启动失败且重新设置无效

### ISSUE THREAD

**Issue by Zplusless** [newlooper/VirtualSpace#130]
version：build 0.2.1104
os：win11 2404   build 26100.2605

开机启动失败，尝试重新再设置中配置，弹窗要求以管理员权限启动。但是管理员权限下设置，有会出现如下问题，点击确定无效。
![image](https://github.com/user-attachments/assets/139853f9-8dc8-4334-a3bc-c9c8e7fc0103)

**Comment by newlooper** [comment]
- 按`Win+R`打开"运行"。键入`taskschd.msc`回车，进入 **计划任务程序**
- 左侧展开 **任务计划程序库**
- 点击 VirtualSpace 项，然后右键，选择删除文件夹
- 以`管理员权限`运行 VirtualSpace.exe
- 再次设置开机启动

**Comment by Zplusless** [comment]
谢谢

---- 回复的原邮件 ----
| 发件人 | Dylan ***@***.***> |
| 发送日期 | 2024年12月17日 19:21 |
| 收件人 | newlooper/VirtualSpace ***@***.***> |
| 抄送人 | MonsterZ ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [newlooper/VirtualSpace] 开机启动失败且重新设置无效 (Issue #130) |

按Win+R打开"运行"。键入taskschd.msc回车，进入 计划任务程序
左侧展开 任务计划程序库
点击 VirtualSpace 项，然后右键，选择删除文件夹
以管理员权限运行 VirtualSpace.exe
再次设置开机启动
