### ISSUE TITLE
[bug] VirtualSpace stopped opening on Windows 10 22h2.

### ISSUE THREAD

**Issue by ghost** [newlooper/VirtualSpace#16]
Hey, 
When trying to open Virtual Space on Windows 10 22H2. I keep getting .net not installed error. Even though I have installed .net core version 6, version 5, and version 3.
I keep getting this error.
![Clip_20221107_230908](https://user-images.githubusercontent.com/110556802/200416223-4b7b79c7-aab2-490f-a5de-818485d20e17.png)

**Comment by newlooper** [comment]
download and install x64 version (not x86)

**Comment by direrFlood** [comment]
it is installed still experiencing the same issue!

**Comment by newlooper** [comment]
read the release note.
download the corresponding version.
run program on another pc, and see difference.

**Comment by direrFlood** [comment]
indeed i got the x64 version it is not working on two pcs... so a huge prob. that it's not my two PC's issue.

**Comment by newlooper** [comment]
check your installation in windows control panel

![image](https://user-images.githubusercontent.com/13162531/200548574-f7c48d5e-fcf2-4b84-9ad0-4063ebf30415.png)

**Comment by direrFlood** [comment]
All installed still the same issue!

**Comment by newlooper** [comment]
setup a VM on your pc: virtualbox, vmware workstation, or hyper-v...
install win10 or win11 in one of the VMs.
and then try all releases of VirtualSpace.
