### ISSUE TITLE
[Bug] Cube3D plugin is not working on windows 11 22H2

### ISSUE THREAD

**Issue by ghost** [newlooper/VirtualSpace#17]
Hey,
When trying to use Cube3D plugin, I get the error that I need to install .net. Even though I have all 3 versions installed: Version 3, 5, 6.(all hosting bundle(full)).
Everytime I try to open cube3d i get this error message: 
![Clip_20221107_230908](https://user-images.githubusercontent.com/110556802/200416687-0e107f5a-de2b-4c41-9b90-0568107f69bd.png)

**Comment by newlooper** [comment]
it's not a bug, Cube3D in release files build with `.netcore3.1` ( as the release note said) due to file size. 
just click `yes` and download from ms site then install `.netcore3.1`.

**Comment by direrFlood** [comment]
it is installed still experiencing the same issue!

**Comment by newlooper** [comment]
read the release note.
download the corresponding version.
run program on another pc, and see difference.

**Comment by newlooper** [comment]
check your installation in windows control panel

![image](https://user-images.githubusercontent.com/13162531/200548574-f7c48d5e-fcf2-4b84-9ad0-4063ebf30415.png)

**Comment by direrFlood** [comment]
downloaded 3.1.3.0 5.0.16 5.0.17 6.0.10 still the same issue! I

**Comment by newlooper** [comment]
Closed due to cant reproduce.

**Comment by Zplusless** [comment]
Same problem, but solved after installing .net 3.1.30 runtime. So can you add the .net version info in the README.MD?
Since .net 3.1 has reached end of life. People may only install .net 6 and later version.

**Comment by newlooper** [comment]
try this

https://github.com/newlooper/VirtualSpace/issues/21
