### ISSUE TITLE
Feature Request Make A pin lock for specific desktops.

### ISSUE THREAD

**Issue by ghost** [newlooper/VirtualSpace#18]

**Comment by micoro** [comment]
You mean having a window only on desktop 1 and 3 but not on desktop 2?
I fear that it would be more of a Windows Virtual Desktop feature rather than a VirtualSpace thing.

**Comment by direrFlood** [comment]
sorry for being unclear.
I meant to lock a desktop with simple pin, For example if you want to go to gaming desktop you need to enter a pin code for example: 1782. 
It is just a suggesstion idk if it is really practical what do you think?
