### ISSUE TITLE
ONLY wants .net core 3.1.0?  vs 3.1.2?

### ISSUE THREAD

**Issue by Skrell** [newlooper/VirtualSpace#2]
I have 3.1.2 installed but your application doesn't seem to recognize it and asks for 3.1.0 ; is that correct?

**Comment by newlooper** [comment]
both VirtualSpace.exe and Cube3D.exe is build and running successfully on `.net core 3.1.23`, `.net core 5.0.15` and `.net core 6.0.3` currently, those are lasted version of framework by now.

it is suggested build the projects yourself use visual studio 2022 if you have `different framework version` in your system.

if you prefer the exes in release zip, you may download `.net core 3.1.23 runtime` from MS site and install it on you system. 

perceptually, it is enough to satisfy the major version, but in my testing, the minor version must also be satisfied.
