### ISSUE TITLE
can youu make cube3d plugin works with framework 6.0+ like the regular virtual space?

### ISSUE THREAD

**Issue by ghost** [newlooper/VirtualSpace#21]
can you make cube3d plugin works with framework 6.0+ like the regular virtual space?

**Comment by newlooper** [comment]
you can build .net 6.0 version yourself, the diff is file size bigger than 3.1 version, so i did not put it in release files.
the project location is VirtualSpace\Plugins.sln\Cube3D.

**Comment by zyazan** [comment]
hello gentlemen
how to build cube3d with 6.0? I am novice

**Comment by newlooper** [comment]
use this Cube3D.exe, its a .net 6.0 version.
[Cube3D.zip](https://github.com/newlooper/VirtualSpace/files/10111744/Cube3D.zip)
