### ISSUE TITLE
can you fix that virtual space can't be set in locations with special strings like: ' ' '-' 

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#22]
can you fix that virtual space can't be set in locations with special strings like: ' ' '-'

**Comment by newlooper** [comment]
what is the full path like.

**Comment by zyazan** [comment]
C:\Users\adam_5\OneDrive - Hebrew_University\Documents\Programs - By -
Me\VirtualSpace

**Comment by newlooper** [comment]
its a `OneDrive` issue, not `SPACE` or `DASH`.
just move VirtualSpace out of OneDrive.

**Comment by zyazan** [comment]
Can you fix the overdrive problem?On 29 Nov 2022, at 11:38, Dylan Cheng ***@***.***> wrote:﻿
its a OneDrive issue, not SPACE or DASH.
just move VirtualSpace out of OneDrive.

**Comment by newlooper** [comment]
Unfortunately, OneDrive is not a normal dir, \Windows\explorer.exe monopolize it, its focus on sync static resources, not a running program.
