### ISSUE TITLE
move google chrome tab to another virtual desktop?

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#24]
Hey,
Is it possible to make a rule to move a google chrome tabs based on the **tab name** or **URL** to another virtual desktop? This way I can keep my non related work stuff automatically moved to my fun virtual desktop.

**Comment by newlooper** [comment]
windows belongs to Windows system, with many API to call.
a tab belongs a window, not much API to access.
VirtualSpace focus on `Desktop` and `Window`.

but if you are interesting about how to control elements of a window, your could search subject about: `Windows UI Automation`
