### ISSUE TITLE
Windows focus should be restored when navigating to a desktop

### ISSUE THREAD

**Issue by oysteinlunde** [newlooper/VirtualSpace#29]
#### Description
In Windows 11 "native virtual desktop", when navigatig to a virtual desktop, the focus of the last active window is restored (the windows that was in focus the last time the desktop was active gets the focus resored). When navigating to a desktop with VirtualSpace, the windows focus is not restored. 

This makes it neccessary to manually (using ALT+TAB or the mouse) to select the window to recieve the focus. 

Fixing this whould make VirtualSpace even more valuable 👌😊

#### To Reproduce
[1] Start Notepad on desktop 1 and start writing something
[2] Switch to desktop 2 using the keyboard
[3] Start Notepad on desktop 2 and start writing something
[4] Switch back to desktop 1 using the keyboard

##### Expected behaviour
The Notepad windows on desktop 1 should be in focus and you should be able to continue to write in Notepad from where the cursor was prior to [2]

##### Actual behaviour
No windows on desktop 1 is in focus so you have to manually select Notepad (with ALT+TAB or the mouse) on desktop 1 before you can continue writing.

#### Context
This behaviour is observed when the Cube3D plugin is active

**Comment by newlooper** [comment]
edit `<VirtualSpace>\Plugins\Cube3D\settings.json` 

```json
{
  "AnimationDuration": 500,
  "CheckAliveInterval": 10,
  "SelectedEffect": 0,
  "ForceOnTop": false <---------------------------
}
```

restart Cube3D or VirtualSpace.

**Comment by oysteinlunde** [comment]
That solves the problem. Thank you so much for your support 👍
