### ISSUE TITLE
Unsupported Windows version

### ISSUE THREAD

**Issue by airda2895** [newlooper/VirtualSpace#3]
![image](https://user-images.githubusercontent.com/45570407/173779953-362a9a2c-1fbe-434a-9aa8-6ececaca8a39.png)

I have Windows 11 Home, 22000.739 build.

**Comment by newlooper** [comment]
Hi~

the program running ok on my test platform (Windows 11 Home, 22000.318), and im upgrading windows to 22000.739 to test again after a while.

which package you download? i use [VirtualSpace_0.1.144.661_netcore3.1_win-x64.zip](https://github.com/newlooper/VirtualSpace/releases/download/Build-0.1.144/VirtualSpace_0.1.144.661_netcore3.1_win-x64.zip)
