### ISSUE TITLE
Back up settings?

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#30]
Hey,
Is there a way to backup settings/export the settings to import them later on?

**Comment by newlooper** [comment]
hmmm~

`settings backup` is a low priority feature, may implement in the subsequent version.

**Comment by craziedde** [comment]
@newlooper what is the best way to import/export settings when a new version released? Is there any trick on "merging" setting into your new release?

**Comment by newlooper** [comment]
a direct upgrade is sufficient.
unless otherwise specified in change log, for new versions of the program, no reconfiguration is required.

**Comment by craziedde** [comment]
![image](https://user-images.githubusercontent.com/2974843/227777913-44243361-78af-427e-98d3-c2fe807f225c.png)

I have a minor issue tho... still showing old Cube3D setting after update..
But that's no worries.. I will figure it out... thank you so much for quick response...
