### ISSUE TITLE
Settings window

### ISSUE THREAD

**Issue by mpapini64** [newlooper/VirtualSpace#32]
Sorry, can you improve this window as the configurations are poorly visible.
Scrolling is not easy.
![image](https://user-images.githubusercontent.com/51324327/215253127-bd95e034-4b0d-40f9-b863-0480039e1cac.png)
I always wondered if there was an entry under the setting:
"Hide Main View when program start"
Maybe don't put it "fixed"

**Comment by newlooper** [comment]
hmm~

This is an old `HDPI / scaling` issue with `WinForms`.

I'll fix it (to an extent) in a subsequent version of VirtualSpace.

Although this problem can be completely circumvented by using WPF as the 'settings window' interface, this will significantly increase the size of the program, which is not worth the loss, so `WinForms` will still be used.

**Comment by mpapini64** [comment]
Ok, with this latest version the settings window works fine.
