### ISSUE TITLE
Option To Switch Desktop By Scrolling On Taskbar Or Scrolling With Hotkey

### ISSUE THREAD

**Issue by TooSpooky** [newlooper/VirtualSpace#33]
Hello,

So far liking your implementation of the concepts, was looking for something just like this. Only complaint is similar to one already posted related to keeping windows on a certain monitor pinned/always visible if thats at all possible, otherwise it's great.

One thing I'd like implemented if it's not already possible is the ability to scroll on the taskbar to switch desktops or set a hotkey to press and scroll (apologies if it's already possible)

Thanks for your time and take care!

**Comment by newlooper** [comment]
you mean use mouse wheel to switch virtual desktop, right?

**Comment by micoro** [comment]
What you want could be achieved with [Virtual Desktop Enhancer](https://github.com/vichzp/virtual-desktop-enhancer/tree/customizations)
The repo I linked should be the most active one currently.

**Comment by TooSpooky** [comment]
Thanks @micoro, I currently use another one at least just for the scrolling bit actually, but it would be nice not to have to run two programs.

@newlooper Yes I do, primarily by hovering over the taskbar or holding down a hotkey.

**Comment by newlooper** [comment]
Scrolling on the taskbar is a good option.
done in Build-0.1.429

**Comment by TooSpooky** [comment]
Sweet, thanks. Works like a charm. I appreciate it.

**Comment by TooSpooky** [comment]
I would also add it would be preferable to have the option to only scroll on the taskbar when on the desktop, currently it's still detecting the scroll while for example in a fullscreen game.

**Comment by TooSpooky** [comment]
Thanks for the quick updates @newlooper Really appreciate it. 

With the newest version checking for if the taskbar is displayed, I can no longer scroll up to go back to the previous desktop, only scroll down to go to the next. I loaded up the old version before the latest and it works.

**Comment by newlooper** [comment]
try run VirtualSpace with Administrator.

**Comment by TooSpooky** [comment]
Doesn't seem to fix it, I run it as admin anyway to be able to check the launch at startup

**Comment by newlooper** [comment]
can not replicate the issue, on my PC.
but i will try another way to determine Taskbar visibility, in next version.

**Comment by TooSpooky** [comment]
Appreciate it man, no clue why I'm having the issue.
