### ISSUE TITLE
White screen when switching between desktops using virtual space.

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#34]
Hey,
When I try to switch to another desktop using virtual space 
1) Win + Tab
2) clicking on another desktop
3) a white screen shows me:
![Clip_20230208_163408](https://user-images.githubusercontent.com/119108387/217559981-15ed1e5e-bff5-4ef7-bb07-c0841a18780d.png)
4) to dismiss the white screen you need to do multiple clicks until it goes/dismisses
I am using windows 11 22h2 build 22621.1194
virtualspace Build-0.1.430
5) I have multiple errors log files:
https://1drv.ms/u/s!AhB8mTrEkdjsunsaHt38jL0OOn6M?e=oEip4G

**Comment by newlooper** [comment]
[22621.1194](https://support.microsoft.com/en-us/topic/january-26-2023-kb5022360-os-build-22621-1194-preview-f6973dbe-bcc4-402a-8b9a-0541b0959403) is a preview version of Win11, which is currently not supported by VirtualSpace, just as the Windows Insider version is not supported.

**Comment by bigplayer-ai** [comment]
> [22621.1194](https://support.microsoft.com/en-us/topic/january-26-2023-kb5022360-os-build-22621-1194-preview-f6973dbe-bcc4-402a-8b9a-0541b0959403) is a preview version of Win11, which is currently not supported by VirtualSpace, just as the Windows Insider version is not supported.

I am not using preview/windows insider version :O I downloaded the image from the official microsoft website.

**Comment by bigplayer-ai** [comment]
![Clip_20230208_182759](https://user-images.githubusercontent.com/119108387/217590907-17f79e2c-b9b9-4a6d-a52a-3d1ae098344e.png)

**Comment by bigplayer-ai** [comment]
> ich is currently not supported by VirtualSpace, just as the Windows Insider version is not supported.

Ok accroding to this microsoft webpage. For commericial users preview version are considered as a stable one 
![Clip_20230208_184930](https://user-images.githubusercontent.com/119108387/217596854-cd9aaf60-6e6e-429a-8608-d1216a165a94.png)
https://insider.windows.com/en-us/preview-windows

**Comment by newlooper** [comment]
For everyday use, it can be seen as equivalent to the stable version, but not for third-party software. VirtualSpace will not make compatibility changes until Microsoft officially pushes out a stable version.

**Comment by bigplayer-ai** [comment]
Do you have any idea how i stop microsoft from pushing preview releases to my Windows?On 8 Feb 2023, at 19:06, Dylan Cheng ***@***.***> wrote:﻿
For everyday use, it can be seen as equivalent to the stable version, but not for third-party software. VirtualSpace will not make compatibility changes until Microsoft officially pushes out a stable version.

**Comment by bigplayer-ai** [comment]
virtualspace is doing the same thing with the new update of windows 11 
[February 14, 2023—KB5022845 (OS Build 22621.1265)](https://support.microsoft.com/en-us/topic/february-14-2023-kb5022845-os-build-22621-1265-90a807f4-d2e8-486e-8a43-d09e66319f38)

**Comment by newlooper** [comment]
my OS is build 22621.1265 too, but never see this problem before.

**Comment by bigplayer-ai** [comment]
Oh after digging around it was MicaForEveryon (another application) fault that messes with your application.I hope this information help someone.On 15 Feb 2023, at 16:31, Dylan Cheng ***@***.***> wrote:﻿
my OS is build 22621.1265 too, but never see this problem before.
