### ISSUE TITLE
Crash whenever I use a hotkey

### ISSUE THREAD

**Issue by kranix0** [newlooper/VirtualSpace#35]
Great app, thank you! I've got desktop switching set to Alt+Shift+{number}. It works well on my personal Windows 10 laptop. On my work laptop (Win11 Enterprise 21H2), it crashes whenever I try a hotkey. The logs don't contain anything noteworthy.

**Comment by newlooper** [comment]
can not replicate the issue, on my PC.
but you can try other key combinations, and trying not to include `SHIFT`

**Comment by kranix0** [comment]
Avoiding Shift fixed it. Thanks!

**Comment by newlooper** [comment]
for more info about why not use `SHIFT`, see this [issue](https://github.com/microsoft/terminal/issues/3001#issuecomment-545685572).
