### ISSUE TITLE
Request: show open windows for the selected app only

### ISSUE THREAD

**Issue by kranix0** [newlooper/VirtualSpace#36]
Back when I used MacOS, I would use four fingers on the pad to swipe up, which would show all open windows, and swipe down to show open windows _for the current app_. The former can be replicated on Windows with Task View, but there's no built-in equivalent for the latter. I've been able to get the latter by making use of a feature in [BetterDesktopTool](https://www.betterdesktoptool.com/), mapping the hotkey to the gesture.

BetterDesktopTool hasn't been updated in years. It would be awesome to have this feature built into VirtualSpace.

**Comment by newlooper** [comment]
i will think about it.

**Comment by newlooper** [comment]
implemented in Build-0.1.441.

**Comment by kranix0** [comment]
Amazing… thank you for implementing this so quickly! It works very well.

Is there a way to show a preview of the windows for a single app on the same desktop only? When all the desktops are shown at once, each window is very small and hard to distinguish.

[Here's an example](https://osxdaily.com/2011/11/24/show-all-windows-for-an-app-in-os-x-lion-with-mission-controls-expose/) from Mac OS. It basically removes the need to use the taskbar to switch windows.
