### ISSUE TITLE
How can I move google chrome work profile to another desktop? What could be my rule?

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#37]
Hey,
What could be the difference between [multiple profiles][1] on Google Chrome? I want to make specific rules for specific chrome profiles:
What is the difference between different profiles on Google Chrome out of these options?

1) Windows Tile.
2) Process Name.
3) Process Path.
4) Window Class.

The different profile shortcuts open the same executable called: chrome.exe.
The shortcuts only differ in shortcut arguments.

Picture for Google Chrome profiles demonstration:
[![Google Chrome Profiles][2]][2]
[![Google Chrome Profiles 2][3]][3]

  [1]: https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform=Desktop
  [2]: https://i.stack.imgur.com/ZVZOq.jpg
  [3]: https://i.stack.imgur.com/5R9c7.jpg

**Comment by newlooper** [comment]
hmmm~

To match shortcut arguments, Rules need new option about the `CommandLine` of a `Process`.
which will implement in next version.

**Comment by bigplayer-ai** [comment]
> hmmm~
> 
> To match shortcut arguments, Rules need new option about the `CommandLine` of a `Process`.
> 
> done in Build-0.1.436 version.

Now how can I use this rule for my work chrome?

**Comment by bigplayer-ai** [comment]
THANKS
