### ISSUE TITLE
切屏快捷键不支持无限切换虚拟窗口

### ISSUE THREAD

**Issue by EmberOfAsh** [newlooper/VirtualSpace#4]
hi，有一个小建议，希望作者考虑下。
当我有4个虚拟窗口时，我希望可以通过 `CTRL` + `WIN `+ `←/→` ，从A屏幕一直连续切换到D屏幕。
现在软件只能支持水平的连续切换。 
 
|  A  |   B  |
| --- | --- |
|  C  |   D |

十分感谢！

**Comment by newlooper** [comment]
EN: i have added this feature, you can see relevant options in the `General` page of App Controller.

CN: 该特性已被加入程序，你可以从控制界面的`通用`页看到相关的配置项。

**Comment by EmberOfAsh** [comment]
完美，感谢作者！
