### ISSUE TITLE
Are the Common Windows rules of profiles are "Or" or "And" Operated?

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#49]
Hey,
Are the Common Windows rules of profiles are "Or" or "And" Operated?

![Clip_20230305_111632](https://user-images.githubusercontent.com/119108387/222952020-5ded4f21-6f89-444f-a858-acf8aaf167eb.png)

**Comment by newlooper** [comment]
yes, but it can't be done in the dialog, only be edit in `<ProfileName>.rules` file.

step:

1. close VirtualSpace
2. open VirtualSpace\Profiles\Default.rules
3. find your rule by name:

```json
"Expression": {
      "id": "a1d7f440-94a3-4049-99ff-8359db6e6712",
      "condition": "and", // <-------------- change "and" to "or"
```
