### ISSUE TITLE
Add possibility to hide pinned windows

### ISSUE THREAD

**Issue by micoro** [newlooper/VirtualSpace#5]
This is a small feature request.
Currently if the "show on all desktop" option is selected a window cannot be hidden from the desktop overview.

In my opinion it could be useful to reduce the clutter on the overview. 

BTW: amazing work, I have looked for something like this that made the virtual desktop usable for more than a year. I have ahk setted up but the lack of this kind of overview was a killer for me: I use this overview on linux (kde).

![image](https://user-images.githubusercontent.com/39342083/187093865-10c711b4-3183-43a8-aacd-279158ddd9e5.png)

**Comment by newlooper** [comment]
done.

**Comment by micoro** [comment]
that was fast. 
tried and it works.

thank you!
