### ISSUE TITLE
[Feature request] Cube3D easy ease animation

### ISSUE THREAD

**Issue by gamesliona** [newlooper/VirtualSpace#51]
hello, I found your app today and it's amazing!
at the moment the transition is linear, same speed at all times. it would be cool if had some sort of a easy ease animation. 
so the speed would go: slow -> fast -> slow.

also sometimes it lags when switching but idk if thats more of a Windows issue rather than ur app

**Comment by newlooper** [comment]
will publish in next version.

**Comment by gamesliona** [comment]
:) cool

**Comment by bigplayer-ai** [comment]
Can you explain to me what is the easy ease animation?

**Comment by gamesliona** [comment]
this is so cool now! thanks man, youre a genius
