### ISSUE TITLE
Win11 insider builds not supported?

### ISSUE THREAD

**Issue by jarusaurus** [newlooper/VirtualSpace#54]
immediately on windows update, had this popup and the app shutdown. 
Guess needs to be updated. 
any workaround? 
would this be the case on every update?

![image](https://user-images.githubusercontent.com/80814501/223100666-91346727-66c4-4159-8161-0793a4383544.png)

**Comment by newlooper** [comment]
insider builds are not supported in most cases and generally have to wait until the official version is released for compatibility updates.

**Comment by bigplayer-ai** [comment]
insider builds are not supported

**Comment by jarusaurus** [comment]
YES!! THIS WORKS!!
![image](https://user-images.githubusercontent.com/80814501/226397485-46621d22-4577-40a0-b765-696127e459eb.png)

Thank you very much. 

Works with the plugins too.

Stay on this version or can I update it?

**Comment by newlooper** [comment]
> try this build, tested on win11 insider 10.0.25314.1010
> 
> [VirtualSpace.zip](https://github.com/newlooper/VirtualSpace/files/11017764/VirtualSpace.zip)

This is a separate version, the production version in release page will not include support for win11 insider.

Microsoft often makes incompatible changes in insider builds, support for insider builds tends to lag behind for a while.

**Comment by jarusaurus** [comment]
Understandable. Hope they don't break anything soon. Thanks again for this support. 
Closing this for now.
