### ISSUE TITLE
Drag and drop messes with the created rules

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#57]
Hey,
When I drag and drop something to a created rule process, for example, chrome.exe, I receive this error:
![Clip_20230308_225943](https://user-images.githubusercontent.com/119108387/223848766-c875bca2-9816-476c-aaf0-05e900371606.png)
I just dragged an image to the website and received the same issue.

**Comment by newlooper** [comment]
will be fixed in next version
