### ISSUE TITLE
希望设置窗口成为一个正常的窗口

### ISSUE THREAD

**Issue by wayneguan26** [newlooper/VirtualSpace#59]
可以调整大小
不要一直置顶

**Comment by mdear-lsn** [comment]
Title : Hope to set the window to be a normal window

Comment : can be resized
don't stay on top

**Comment by newlooper** [comment]
可以调整大小是合理的，这已经通过用 WPF 版的设置窗口替换 WinForm 版的而实现了。但是设置窗口`置顶`则是有意设计如此，其原因为：

1. 在 VirtualSpace 主视图已经显示的情况下，此时打开设置窗口(比如：用全局快捷键)，如果设置窗口不置顶，则其将被主视图遮挡导致无法交互。

2. 与 VirtualSpace 主视图比起来，设置窗口的出现概率小的多，存活时间也短的多，其置顶状态可以提醒并鼓励使用者用完就关闭，尽早让运行时和系统回收其占用的资源。

以上。
