### ISSUE TITLE
[feature request] add active screen position display to every screen

### ISSUE THREAD

**Issue by craziedde** [newlooper/VirtualSpace#61]
Hi,

Love the program and find it very useful.
Here is my request in screenshot attached below.
Please let me know if I need to explain it more.
![image](https://user-images.githubusercontent.com/2974843/226775408-ff354b94-4748-4129-b9dc-ee9211ed0b31.png)

**Comment by craziedde** [comment]
The reason why I like this on every screen is that it's very "visual" and helps determain which desktop you are currently on at the glance. (works better than desktop names actually)

**Comment by newlooper** [comment]
You need to be more specific, now I can only guess：

you need an indicator (show by shortcut) to tell you which desktop you are currently in (`Nothing to do with switching desktops`)  (kind of like `Settings > System > Display` \ `Identify` button does)

OR

you want Cube3D only show the NotificationGrid (without animation) WHEN switching desktops?

**Comment by craziedde** [comment]
Yes correct

1.Yes → NotificationGrid (without any animation, briefly appears WHEN switching desktops)
2. Yes → NotificationGrid will be show on ALL screens

Please see sample attached
![image](https://user-images.githubusercontent.com/2974843/227259591-f540590b-af9d-42be-8b75-e5022634e119.png)

**Comment by craziedde** [comment]
And IF possible to add the **name of the current desktop** right on top the NotificationGrid as title 

This would make it crystal clear of your "Current desktop" while switching, but may require some dev afford.

**Comment by craziedde** [comment]
Extra feature (hope I'm not asking for too much :)

Add desktop name as title for NotificationGrid
Screenshot attached below

![image](https://user-images.githubusercontent.com/2974843/227783877-36ca4f17-9319-4c6f-b4aa-c68b6d06e34e.png)
