### ISSUE TITLE
Virtual Space does not work with mouse trackpad correctly.

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#62]
Hey,
When launching Virtual Desktops, background/task view using mouse trackpad gestures.
![Clip_20230322_143001](https://user-images.githubusercontent.com/119108387/226905296-48f71357-59ac-4ee1-8cc7-7d5da01d49e1.png)

Virtual Space does not launch it is the main interface, Instead, Windows shows its regular task view. Can you solve this?
Check the video attached.

[https://ufile.io/byhdnrv7](https://ufile.io/byhdnrv7): https://ufile.io/byhdnrv7

**Comment by newlooper** [comment]
hmmm~

`custom shortcut` is your friend.

https://www.youtube.com/watch?v=fPK_k51PM1U
