### ISSUE TITLE
No Desktop Background in Desktop Switcher Mode

### ISSUE THREAD

**Issue by Zackorus** [newlooper/VirtualSpace#63]
First I have to say love this program. I am just running into a small issue where the desktop background instead of appearing as it should when I press L-Win+Tab. I get a white background with a red X. How can I fix this? 

Windows 10 OS Build 1776.107 
Version 1809

**Comment by newlooper** [comment]
OS too old.

**Comment by Zackorus** [comment]
Strangely enough, when I downloaded the Net Framework 7 it worked. This software is awesome btw, I was waiting for something like this for years.
