### ISSUE TITLE
How do you manage multiple rule profiles?

### ISSUE THREAD

**Issue by mpapini64** [newlooper/VirtualSpace#65]
I tried to go to the "C:\Program Files\VirtualSpace\Profiles" folder where the Default.rules file is, make a copy called Office.rules, restart VirtualSpace, but from the settings it doesn't let me choose Office.
In the file "C:\Program Files\VirtualSpace\settings.json" there is the possibility to change the entry but I would prefer not to touch that file. 
This is the related item: 
```
   "CurrentProfileName": "Default",
   "Version": "1.0",
   "LogConfig": {
     "ShowLogsInGui": false,
     "LogLevel": "EVENT"
   },
```
The reason is because at home I only have one monitor and therefore I created 3 virtual desktops, but in the office I physically have 3 monitors and therefore I don't need virtual desktops, but I still wanted to use VirtualSpace to direct my apps to the 3 different physical monitors departure, as well as I do at home with virtual ones.

**Comment by newlooper** [comment]
hmmm~

`settings backup`, `multiple profiles` will be implemtented in next version.

plan:

### 1. user could choose a local path to store all config files.
> so they can sync those files with Cloud-Storage like OneDrive, DropBox, ...

### 3. manage multiple profiles through GUI.
> edit json file is not friendly.
