### ISSUE TITLE
Using an "Alt" keyboard shortcut is not ideal

### ISSUE THREAD

**Issue by Zedbloc** [newlooper/VirtualSpace#66]
This may not be something you can address, but if I use Ctrl + Alt + Left/Right/Up/Down to switch workspaces, something steals the focus of the "Ctrl + Alt" and I have to take my finger off Alt and press it again to switch to another workspace. So, I can't hold down Ctrl + Alt and hit left,right,up,down over and over. But I can do this fine using the default Win + Ctrl + Left/Right/UpDown.

**Comment by newlooper** [comment]
#72
