### ISSUE TITLE
Norton 360 is removing virtualspace.exe and updater.exe due to WS.Reputation.1

### ISSUE THREAD

**Issue by mdear-lsn** [newlooper/VirtualSpace#67]
https://community.norton.com/en/forums/wsreputation1-alert-norton

**Comment by newlooper** [comment]
I've encountered this once before, but didn't find the cause, compiled the exact same code again, and the alarm disappeared strangely.

you cloud download the source, and build yourself to test it.

**Comment by newlooper** [comment]
And Google "WS.Reputation.1" for more information.

**Comment by mdear-lsn** [comment]
Under Visual Studio I have succeeded in building the following executables, but I'm unclear on the step in your Readme.md
that states:

put all generated files into main program's plugins Folder eg: plugins\Cube3D

Could you tell me how to do this specifically please?


``` ./Plugins.sln/Cube3D/bin/Debug/net6.0-windows10.0.20348.0/Cube3D.exe
./Plugins.sln/Cube3D/bin/Debug/net6.0-windows10.0.22000.0/Cube3D.exe
./Plugins.sln/Cube3D/obj/Debug/net6.0-windows10.0.20348.0/apphost.exe
./Plugins.sln/Cube3D/obj/Debug/net6.0-windows10.0.22000.0/apphost.exe
./Plugins.sln/Updater/bin/Debug/net6.0-windows/Updater.exe
./Plugins.sln/Updater/bin/Release/net6.0-windows/Updater.exe
./Plugins.sln/Updater/obj/Debug/net6.0-windows/apphost.exe
./Plugins.sln/Updater/obj/Release/net6.0-windows/apphost.exe
./VirtualSpace/bin/Release/net6.0-windows/VirtualSpace.exe
./VirtualSpace/obj/Release/net6.0-windows/apphost.exe
```

**Comment by newlooper** [comment]
structure should like below:

```
./xxx/VirtualSpace.exe

./xxx/Plugins/Cube3D/Cube3D.exe
./xxx/Plugins/Cube3D/plugin.json
./xxx/Plugins/Cube3D/settings.json

./xxx/Plugins/Updater/Updater.exe
./xxx/Plugins/Updater/plugin.exe
./xxx/Plugins/Updater/settings.exe
```

where `xxx` is VirtualSpace root folder.

**Comment by mdear-lsn** [comment]
Thanks, I've extracted the json files from the zipfile and have substituted links to the newly built executables and your tool is coming up now.  Oddly the executables didn't run when I simply copied them from their built locations, but the softlinks worked.  I've also wrestled with my Norton 360 virus scanner and creates rules preventing it from quarantining your executable files.
