### ISSUE TITLE
How to migrate configuration from older version of VirtualSpace, how to build latest VirtualSpace, how to run plugins ?

### ISSUE THREAD

**Issue by mdear-lsn** [newlooper/VirtualSpace#74]
I git-pulled last week's version of VirtualSpace and built the solution successfully with VS 17.2.

I then copied built plugin content as shown below:

``` $ find ~/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins/Cube3D
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins/Cube3D/Cube3D.exe
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins/Cube3D/plugin.json
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins/Cube3D/settings.json
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins/Updater
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins/Updater/plugin.json
/c/Users/smdea/workspace/git/VirtualSpace/VirtualSpace/bin/Release/net6.0-windows/Plugins/Updater/Updater.exe
```

I ran the tool and I proceeded to create a rule set.
I didn't see any way to export the rule set.
 
The plugins show up in the VS control panel and I can configure them, but I still don't understand how to use them and I haven't seen any instructions for the same.

Today I saw there was an update, so I git- pulled the latest and tried to build, but received the following error:
Invalid option '11' for /langversion net6.0-windows

![image](https://user-images.githubusercontent.com/124737904/233729558-fa13d35c-fa5a-4e16-a580-0f9687a4e73d.png)

Thus, I downloaded the prebuilt zipfile and ran it outside the git environment, which worked but my rules did not appear.

Please provide instructions how to build the latest codebase so I can run it in place, otherwise please tell me how to migrate my ruleset outside the git environment into the extracted zip execution directory.

I'm setting my Task Scheduler actions as : 1. Start VirtualSpace.exe  2. Start Updater.exe  3. Start Cube3D.exe

Please also provide instructions on how to actually use the plugins.

**Comment by newlooper** [comment]
### about rules

1. if your Norton not warning again, just use the files downloaded from the release page. there is no significant benefits of build the project yourself, if you dont want analyze the source code of VS.
2. the files of `Rules` is saved in the `<VirtualSapce>\Profiles\*.rules`, before you migrate those files to the new version of VS, make a backup for them❗
4. put your old *.rules files into the new `<VirtualSapce>\Profiles\`, then start VS.

### about plugins

there is no need to set Update.exe and Cube3D.exe in the Task Scheduler, they are taken care by VS, the correct dir structure can be found in the zipfile of the release page.

- Updater.exe is a silent app which only run once at VS start, if no updates for VS, it just quit silently.
- Cube3D.exe using WindowsMessage to interact with VS, thus VS will continue runing even if Cube3D was crash.

  - if all is well, when user use the shortcut: `LWin+LCtrl+<↑ ↓ ← →>` to switch virtual desktop, Cube3D will show transition effects to improve UX, nothing more.

**Comment by mdear-lsn** [comment]
Thanks very much!  I have migrated my rules to a released zipfile extracted location and the tool is working beautifully.  I appreciate the quick turnaround with feature requests, I am now recommending this tool to others in my network.  Do you accept donations to help support your hard work ?

**Comment by mdear-lsn** [comment]
Can I buy you a coffee?  https://www.buymeacoffee.com/

**Comment by newlooper** [comment]
I haven't decided whether to set up a donation portal, maybe in the future.
