### ISSUE TITLE
Alt key is being ignored when configing Control Desktop/Switch/Switch to Desktop x

### ISSUE THREAD

**Issue by mdear-lsn** [newlooper/VirtualSpace#75]
I am raising this issue against version 0.2.502.805 of the released VS software.

I am checking "Alt" and D1-D6 as I did in the previous (last week's) version of VS.

In the latest version, the "Alt" key is ignored and the raw D1-D6 keys are invoking the desktop switch, which is causing problems.

I tried "Clear and Save" followed by re-entering the desired key combinations but the same issue was seen thereafter.

Please look into this issue.

System details : 

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DEARONTHEGO
System Manufacturer	Framework
System Model	Laptop (12th Gen Intel Core)
System Type	x64-based PC
System SKU	FRANMACP08
Processor	12th Gen Intel(R) Core(TM) i7-1280P, 1800 Mhz, 12 Core(s), 18 Logical Processor(s)
BIOS Version/Date	INSYDE Corp. 03.05, 2022-08-23
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Framework
BaseBoard Product	FRANMACP08
BaseBoard Version	A8
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.2728"
User Name	DEARONTHEGO\smdea
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	63.7 GB
Available Physical Memory	32.0 GB
Total Virtual Memory	73.2 GB
Available Virtual Memory	33.2 GB
Page File Space	9.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
Virtualization-based security Services Running	Hypervisor enforced Code Integrity
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by newlooper** [comment]
#72

**Comment by mdear-lsn** [comment]
I have left comments against issue #72, the recommended workaround is working for me.  Thanks.
