### ISSUE TITLE
Search bar on main screen to improve user efficiency and productivity

### ISSUE THREAD

**Issue by mdear-lsn** [newlooper/VirtualSpace#76]
I'm finding that sometimes I forgot in which workspace I raised a particular window and I want to search for a window Title and find out where that window can be found.

In the past, before Task View and VS, I would have multiple copies of the same window and this approach was dragging down my productivity.

I also see that Task View has a search function but only for timeline objects and not window objects.

This feature could be a really useful addition to VS and would prevent me from going back to Task View and accessing each workspace, one at a time, scrolling around to check window titles, to find the window I'm looking for.

You could even envision a feature that allows searching on other fields other than window name (ie, on any field possible to set in a rule perhaps).

**Comment by newlooper** [comment]
VirtualSpace now have a WindowFilter in its MainView, When the MainView is shown, you could use [Double LShift] to open the WindowFilter.

**Comment by mdear-lsn** [comment]
Thanks, this feature works very well and removes the need for a hover/tool tip.  I can confirm this feature works for me.
