### ISSUE TITLE
Failed to autogenerate rule from main page workspace subwindow

### ISSUE THREAD

**Issue by mdear-lsn** [newlooper/VirtualSpace#77]
[VS_LogsApr24_2023.zip](https://github.com/newlooper/VirtualSpace/files/11314557/VS_LogsApr24_2023.zip)

Thanks

**Comment by newlooper** [comment]
i don't get it.
you need describe it more specific, or maybe you could capture a screen video to show the case.

**Comment by mdear-lsn** [comment]
Limited-time link, please copy out.  Thanks.  

https://www.dropbox.com/s/x500slakw54r2yw/2023-04-26%2017.16.19.mov?dl=0

**Comment by newlooper** [comment]
try the latest version `0.2.509.562`

**Comment by mdear-lsn** [comment]
The issue is not seen in 0.2.509.562, the autogenerated rule once again works as expected.  Thanks very much for this fix !
