### ISSUE TITLE
Please change keyboard focus to WindowFilter when it is invoked

### ISSUE THREAD

**Issue by mdear-lsn** [newlooper/VirtualSpace#79]
I'm loving the WindowFilter feature!

It would be even better if, when invoked with a double-shift-press the keyboard focus changes to the WindowFilter so I can commence typing immediately without having to move the mouse to the window and clicking to change focus.

Also, I would love to donate to this project as I've been finding it seriously multiplying my productivity.  Your readme doesn't mention any way to do this.  I would like to vote with my dollars !

**Comment by newlooper** [comment]
the WindowFilter will get focus when it opened, it is design so from the beginning.
unless there are another app steal focus from it.
the way to confirm: try a fresh VS in a clean Windows in a VM like VMware, Hyper-V, VirtualBox...

**Comment by mdear-lsn** [comment]
I'm not sure which app is, as you put it, stealing focus.  Is there any way to characterize / determine what is going wrong?  

On my system, focus does not stay with the WindowFilter when I invoke it.  Could you at least allow me to transfer focus to it by pressing the <Tab> key ?  The mousing action is more time consuming.  Thanks.

**Comment by mdear** [comment]
Update : I'm seeing sporadic behavior here on my Windows 10 Pro frame.work laptop, sometimes when I enter the Window Filter I can type immediately, and other times I must move the mouse to the Window Filter area and left click to move focus.  

I'd still appreciate having a <Tab> key on the main view that will allow me to move focus to the Window Filter if it is not there already.

This is a real development machine, not a clean Windows install, and I would still appreciate having this feature.
