### ISSUE TITLE
Crash when connecting/disconnecting monitors

### ISSUE THREAD

**Issue by micoro** [newlooper/VirtualSpace#8]
VirtualSpace crashes when I connect my laptop to the external monitor (or when I disconnect the monitor).
There seems to be no problem if I just use the win+P command to activate or disactivate monitors.
The error/crash happens when physically connecting/disconnecting the monitor (tried with different monitors).

The error message is below
![image](https://user-images.githubusercontent.com/39342083/193581062-81bb94f4-8097-4a8b-b4de-f7deb7e1bbe9.png)

**Comment by newlooper** [comment]
hmmm~

i don't  have a win10 laptop, i use win11 on a PC now.
i have tested hotplug monitor without problem you described.

### Suggested:

just comment line 98 of file: https://github.com/newlooper/VirtualSpace/blob/26def512a87041d7fe18687dab8426a637e054c5/Configuration/Manager.cs#L98

then build the VirtualSpace10 project, run program and see what happens.

**Comment by micoro** [comment]
I tried but it did nothing. 
But it was only a single test and I want to try it again just to be sure I didn't do something wrong.

**Comment by micoro** [comment]
I am won't be able to do the test at least until next week (I am not home).
But I have tried to disconnect and reconnect the monitor I am currently using and VirtualSpace did not crash (tried multiple times). 

It's possible that the changes of the last couple of days have fixed it? I will check again with the monitor back at home next week.

**Comment by newlooper** [comment]
good idea.
the file size of those gifs is too big, so i replace them with a single image.
i will think about it.

**Comment by micoro** [comment]
Confirmed: I can't replicate the problem in the recent versions.
