### ISSUE TITLE
Crashes seen on 0.2.512.563

### ISSUE THREAD

**Issue by mdear** [newlooper/VirtualSpace#80]
I have seen version 0.2.512.563 crash repeatedly.

I'm not sure how I could capture a stack dump for the crash since it happens at unexpected times.

When I do things like unplug my USB-C Thunderbolt connector (connected to a USB-C hub monitor with a DP cable to a third monitor), or switch my USB-C hub display from USB-C input to HDMI input (video switch), I see red error message boxes from VS, which I have seen occasionally with the past few versions.  Despite these occasional red error boxes, I have continued to use VS without any noticable problem or impediment.

However, today, I am starting to see the app crashing and I have had to  restart it multiple times during my working day.

Logs may be found at the following link, please copy out as this link will expire soon :
https://www.dropbox.com/s/hm4qxagf5bmh7zg/VS_LogsMay7_2023.zip?dl=0

**Comment by newlooper** [comment]
you need install the latest Cube3D, Or you can simply disable Cube3D.
