### ISSUE TITLE
VirtualSpace crashes unexpectedly and occasionally

### ISSUE THREAD

**Issue by mdear-lsn** [newlooper/VirtualSpace#82]
This issue is a placeholder for an issue that I'm seeing in which VirtualSpace crashes without restarting itself.

I have my laptop set to reboot daily, so factoring out the expected terminations, if I see a crashdump of an unexpected VirtualSpace termination I will enclose it here.

**Actions :** 
I have replaced the Task Scheduler action created by VirtualSpace with the following (\path\to is not to be taken literally, it is an example anonymized path representing a path that is environment-specific) : 

Start in : Folder where VirtualSpace is invoked from
Program/script : C:\path\to\procdump.exe
Arguments : 
 -ma -w -mk -t  -x C:\path\to\VirtualSpace\CrashDumps C:\path\to\VirtualSpace\VirtualSpace.exe

As per https://learn.microsoft.com/en-us/sysinternals/downloads/procdump

**General :** 
Run only when user (me) is logged on
Run with highest privileges : checked
Configure to : Windows 10

**Trigger :** At log on of any user : enabled

**Conditions :** All unchecked

**Settings :** 
Allow task to be run on demand - checked
Run task as soon as possible after a scheduled start is missed : unchecked
If task fails, restart every : checked, dropdown set to 1 minute, attempt to restart up to : 3 times
Stop the task if it runs longer than : unchecked
If the running task does not end when requested, force it to stop : checked
If the task is not scheduled to run again, delete it after : unchecked
If the task is already running, Stop the existing instance.

**Comment by mdear** [comment]
Update (Jul 10/ 2023)
I'm not seeing this behavior in build 0.2.536.1404
