### ISSUE TITLE
New feature request - save the last rule to fire against a particular window

### ISSUE THREAD

**Issue by mdear** [newlooper/VirtualSpace#89]
I'm having a problem, where I have a large list of rules now, but I'm finding that on startup my Brave browser is appearing on all workspaces because the "Show windows from this app on all desktops" option has been activated. 

This is not what I want.

I have gone over every rule and I do not have a rule configuring Brave to appear on all desktops.

However, every time I do my nightly startup I must go the the main view, right click a Brave browser in one of my workspaces, and deselect this option.

In order to debug this, is there a way you could store alongside each window the last rule that fired against it so this could be retrieved after the fact via an option on the main view window right click menu ?

I should also mention that, whenever there is a system event such as turning on/off a monitor and plugging/unplugging my USB-C Thunderbolt connection to my USB-C Hub monitor, I see a sequence of red boxes stating that there was an error directing a particular window to a particular workspace.  Once the system processing / slowdown that normally happens after these events subsides, VirtualSpace operation returns to normal.  I'm not sure if this is a bug or a feature.  This behavior is very consistent.

**Comment by newlooper** [comment]
- find `Default.rules` or `<YourProfileName>.rules` in `<VirtualSpace>\Profiles\
- open it with a text editor
- search `"PinWindow": true` and `"PinApp": true` (note the `SPACE` after `:`)

if there is a match, then you find the reason, but if not, there is nothing to do with `Rules`.

**Comment by mdear** [comment]
I did so, and found the offending rule much easier with a text editor than the GUI, thanks for the pointer.

Please retain this feature request, however, as having information about what rule ultimately caused a window to be positioned where it is would be extremely useful in debugging unwanted behavior.
