### ISSUE TITLE
desktop index in the tray bar

### ISSUE THREAD

**Issue by micoro** [newlooper/VirtualSpace#9]
Is it possible to alter the tray icon so that it shows the index of the virtual desktop I am currently in?

**Comment by newlooper** [comment]
done.

**Comment by micoro** [comment]
Thank you man. You implemented that immediately!

I find it extremely useful, especially when navigating virtual desktops with the keys (and not the grid view).
I often loose myself, forget my position or simply windows move me to a different desktop because I opened something like a pdf or a program and since an instance was open somewhere else I got transferred there.

I used enhanced virtual desktop until two days ago, it had this information on the tray bar and just two days without it made me notice how useful it was.
