### ISSUE TITLE
0.2.536 stopped loading on Windows 11

### ISSUE THREAD

**Issue by kranix0** [newlooper/VirtualSpace#92]
VirtualSpace 0.2.536 no longer loads on Windows 11. Here is my OS environment:

> Edition	Windows 11 Pro
> Version	22H2
> Installed on	‎Tue ‎14/‎02/‎2023
> OS build	22621.2215
> Experience	Windows Feature Experience Pack 1000.22662.1000.0

The logs don't tell anything useful. info.txt says "Application Start Successfully". Other logs just show "==================================================".

**Comment by sytone** [comment]
API change in windows 11, see https://github.com/MScholtes/VirtualDesktop/issues/67 as a reference to the new GUIDs and API changes.

**Comment by newlooper** [comment]
hi~

MS change many API in `win11-22621.2215`.

i dont have this version, but i build a standalone release for people who already upgrade to `win11-22621.2215`: 
[VirtualSpace_0.2.634.669_net6.0_win-x64(WIN11-22621.2215_ONLY).zip](https://github.com/newlooper/VirtualSpace/files/12485531/VirtualSpace_0.2.634.669_net6.0_win-x64.WIN11-22621.2215_ONLY.zip)

not fully tested, any bugs let me know.

Regards!

**Comment by kranix0** [comment]
Based on 5 seconds of playing with it… it works! I'll report back if I find any problems.

Thanks!

**Comment by Zplusless** [comment]
same problem, solved! Thanks

**Comment by jarusaurus** [comment]
I think along with the API changes, they also changed the dev and beta channels for insider build previews.
With current Dev becoming Canary builds. I am having the same issue but, because i am on canary build Version 23H2 (0S Build 25941.1000)
Any way a version is possible for this one?

**Comment by kranix0** [comment]
I can confirm that this also works on a different machine.

OS Name:	Microsoft Windows 11 Enterprise
Version:	10.0.22621 Build 22621

**Comment by mdear** [comment]
Will this special Windows 11 fix also work on Version	10.0.22631 Build 22631  ??
