### ISSUE TITLE
Pin Window vs Pin App of Window options are reversed, wreaking havoc.

### ISSUE THREAD

**Issue by mdear** [newlooper/VirtualSpace#95]
You appear to have some reversed logic.

When I enter a rule and check the "Pin Application of Window" option and uncheck the "Pin Window" option, 
I would expect in the profile Default.rules file the following encoding to be present:

```
"Action": {
  ...
  "PinWindow": false,
  "PinApp": true,
  ...
}
```

However, the reverse appears to be true.  Please fix this and double check other checkboxes to ensure they behave as expected.

I use the "Pin Application of Window" option only very sparingly as if overused it can seriously clutter the Main View.

![image](https://github.com/newlooper/VirtualSpace/assets/6562082/4c2572be-4e8f-4bdf-a346-c61ce27ae24c)

**Comment by newlooper** [comment]
fixed in new version.
